# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "The command for retrying commands"
  homepage "https://github.com/glynternet/retry"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/glynternet/retry/releases/download/0.3.0/retry_0.3.0_darwin_amd64.tar.gz"
      sha256 "9c2f2963f9bbe6ba4dfaf7ce0658790eadaab60c6506cfd9430975a88cb4e315"

      def install
        bin.install "retry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/glynternet/retry/releases/download/0.3.0/retry_0.3.0_darwin_arm64.tar.gz"
      sha256 "4333e31e03050ad9a6226328d29915d77b911b76946b5fa384a041b0792a45b7"

      def install
        bin.install "retry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/glynternet/retry/releases/download/0.3.0/retry_0.3.0_linux_arm64.tar.gz"
      sha256 "92a828532fcd079d828dfa71316b2de8c254168746d4f23d7abf52f120ca91fb"

      def install
        bin.install "retry"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/glynternet/retry/releases/download/0.3.0/retry_0.3.0_linux_amd64.tar.gz"
      sha256 "67dda44a6f52b3f37ae4ed566ede64a511b9ed5533c6d09a141006d65575ca9a"

      def install
        bin.install "retry"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'retry --help' for usage instructions
    EOS
  end
end
